# -*- coding: utf-8 -*-
"""week2-A107260093-林芷妤.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11JDe_rKU69-UvtW0W7s2BmpVyBFFoRXn
"""

print("Hello World")

import this